INSERT INTO tag (name, description) VALUES
    ('javascript', 'A high-level, often just-in-time compiled language that conforms to the ECMAScript specification. Used primarily for web development.'),
    ('python', 'An interpreted, high-level, general-purpose programming language. Its design philosophy emphasizes code readability with its notable use of significant whitespace.'),
    ('c++', 'A general-purpose programming language created as an extension of the C programming language. Commonly used in system/software requirements and game development.'),
    ('c', 'A general-purpose, procedural computer programming language. It is one of the most widely used programming languages of all time.'),
    ('postgresql', 'The worlds most advanced open-source relational database. Known for its extensibility and SQL compliance.');

INSERT INTO tag (name, description) VALUES
                                        ('typescript', 'A strongly typed superset of JavaScript that compiles to plain JavaScript.'),
                                        ('react', 'A JavaScript library for building user interfaces, maintained by Meta.'),
                                        ('nextjs', 'A React framework for production with server-side rendering and static site generation.'),
                                        ('nodejs', 'A JavaScript runtime built on Chrome''s V8 engine for building server-side applications.'),
                                        ('express', 'A minimal and flexible Node.js web application framework.'),
                                        ('rust', 'A systems programming language focused on safety, speed, and concurrency.'),
                                        ('go', 'A statically typed, compiled language designed at Google for simplicity and performance.'),
                                        ('java', 'A class-based, object-oriented programming language designed to be platform-independent.'),
                                        ('kotlin', 'A modern, concise programming language that runs on the JVM, fully interoperable with Java.'),
                                        ('swift', 'A powerful and intuitive programming language for Apple platforms.'),
                                        ('php', 'A widely-used general-purpose scripting language suited for web development.'),
                                        ('ruby', 'A dynamic, interpreted programming language focused on simplicity and productivity.'),
                                        ('html', 'The standard markup language for creating web pages and web applications.'),
                                        ('css', 'A stylesheet language used to describe the presentation of a document written in HTML.'),
                                        ('tailwindcss', 'A utility-first CSS framework for building custom designs without leaving your HTML.'),
                                        ('sql', 'A domain-specific language for managing and querying relational databases.'),
                                        ('mysql', 'An open-source relational database management system.'),
                                        ('mongodb', 'A NoSQL document-oriented database program.'),
                                        ('redis', 'An in-memory data structure store used as a database, cache, and message broker.'),
                                        ('docker', 'A platform for developing, shipping, and running applications in containers.'),
                                        ('git', 'A distributed version control system for tracking changes in source code.'),
                                        ('linux', 'An open-source Unix-like operating system kernel.'),
                                        ('bash', 'A Unix shell and command language widely used for scripting.'),
                                        ('regex', 'A sequence of characters that defines a search pattern, used for string matching.'),
                                        ('rest-api', 'An architectural style for designing networked applications using HTTP.'),
                                        ('graphql', 'A query language for APIs and a runtime for executing those queries.'),
                                        ('websockets', 'A protocol providing full-duplex communication channels over a single TCP connection.'),
                                        ('jwt', 'A compact, URL-safe means of representing claims to be transferred between two parties.'),
                                        ('oauth', 'An open standard for access delegation, commonly used for token-based authentication.'),
                                        ('algorithms', 'Step-by-step procedures for solving problems and performing computations.'),
                                        ('data-structures', 'Ways of organizing and storing data for efficient access and modification.'),
                                        ('debugging', 'The process of finding and resolving bugs or defects in software.'),
                                        ('performance', 'Techniques and practices for improving the speed and efficiency of software.'),
                                        ('security', 'Practices and tools for protecting software systems from threats and vulnerabilities.'),
                                        ('testing', 'The process of evaluating software to ensure it behaves as expected.'),
                                        ('async', 'Programming patterns for handling operations that run independently of the main thread.'),
                                        ('concurrency', 'The ability of a program to execute multiple tasks seemingly simultaneously.'),
                                        ('memory-management', 'Techniques for controlling and optimizing how a program allocates and frees memory.');